/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobFairsRouteImport } from './routes/job-fairs'
import { Route as BrowseTalentRouteImport } from './routes/browse-talent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardPosterRouteImport } from './routes/dashboard.poster'
import { Route as DashboardFreelancerRouteImport } from './routes/dashboard.freelancer'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobFairsRoute = JobFairsRouteImport.update({
  id: '/job-fairs',
  path: '/job-fairs',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseTalentRoute = BrowseTalentRouteImport.update({
  id: '/browse-talent',
  path: '/browse-talent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPosterRoute = DashboardPosterRouteImport.update({
  id: '/dashboard/poster',
  path: '/dashboard/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFreelancerRoute = DashboardFreelancerRouteImport.update({
  id: '/dashboard/freelancer',
  path: '/dashboard/freelancer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse-talent': typeof BrowseTalentRoute
  '/job-fairs': typeof JobFairsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/freelancer': typeof DashboardFreelancerRoute
  '/dashboard/poster': typeof DashboardPosterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse-talent': typeof BrowseTalentRoute
  '/job-fairs': typeof JobFairsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/freelancer': typeof DashboardFreelancerRoute
  '/dashboard/poster': typeof DashboardPosterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse-talent': typeof BrowseTalentRoute
  '/job-fairs': typeof JobFairsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/freelancer': typeof DashboardFreelancerRoute
  '/dashboard/poster': typeof DashboardPosterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse-talent'
    | '/job-fairs'
    | '/login'
    | '/signup'
    | '/dashboard/freelancer'
    | '/dashboard/poster'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse-talent'
    | '/job-fairs'
    | '/login'
    | '/signup'
    | '/dashboard/freelancer'
    | '/dashboard/poster'
  id:
    | '__root__'
    | '/'
    | '/browse-talent'
    | '/job-fairs'
    | '/login'
    | '/signup'
    | '/dashboard/freelancer'
    | '/dashboard/poster'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseTalentRoute: typeof BrowseTalentRoute
  JobFairsRoute: typeof JobFairsRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DashboardFreelancerRoute: typeof DashboardFreelancerRoute
  DashboardPosterRoute: typeof DashboardPosterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-fairs': {
      id: '/job-fairs'
      path: '/job-fairs'
      fullPath: '/job-fairs'
      preLoaderRoute: typeof JobFairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse-talent': {
      id: '/browse-talent'
      path: '/browse-talent'
      fullPath: '/browse-talent'
      preLoaderRoute: typeof BrowseTalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/poster': {
      id: '/dashboard/poster'
      path: '/dashboard/poster'
      fullPath: '/dashboard/poster'
      preLoaderRoute: typeof DashboardPosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/freelancer': {
      id: '/dashboard/freelancer'
      path: '/dashboard/freelancer'
      fullPath: '/dashboard/freelancer'
      preLoaderRoute: typeof DashboardFreelancerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseTalentRoute: BrowseTalentRoute,
  JobFairsRoute: JobFairsRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DashboardFreelancerRoute: DashboardFreelancerRoute,
  DashboardPosterRoute: DashboardPosterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
