/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JobFairsRouteImport } from './routes/job-fairs'
import { Route as IndexRouteImport } from './routes/index'

const JobFairsRoute = JobFairsRouteImport.update({
  id: '/job-fairs',
  path: '/job-fairs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/job-fairs': typeof JobFairsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/job-fairs': typeof JobFairsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/job-fairs': typeof JobFairsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/job-fairs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/job-fairs'
  id: '__root__' | '/' | '/job-fairs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobFairsRoute: typeof JobFairsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/job-fairs': {
      id: '/job-fairs'
      path: '/job-fairs'
      fullPath: '/job-fairs'
      preLoaderRoute: typeof JobFairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobFairsRoute: JobFairsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
